package com.tourplanner.domainobjects;
// Generated 8 Jan, 2014 11:36:33 AM by Hibernate Tools 3.2.1.GA



/**
 * Tour generated by hbm2java
 */
public class Tour  implements java.io.Serializable {


     private Integer id;
     private String tourId;
     private String name;
     private String description;
     private Integer members;

    public Tour() {
    }

    public Tour(String tourId, String name, String description, Integer members) {
       this.tourId = tourId;
       this.name = name;
       this.description = description;
       this.members = members;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTourId() {
        return this.tourId;
    }
    
    public void setTourId(String tourId) {
        this.tourId = tourId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getMembers() {
        return this.members;
    }
    
    public void setMembers(Integer members) {
        this.members = members;
    }




}


